version: "3.8"

networks:
  api-gateway:
    name: speadsheet-writer
    driver: bridge
  internal:
    name: speadsheet-writer-internal
    driver: bridge

services:
  api-gateway:
    build: .
    command: pnpm start:dev api-gateway
    ports:
      - "3000:3000"
    networks:
      - api-gateway
      - internal
    volumes:
      - .:/app
    depends_on:
      - writer

  writer:
    build: .
    command: "pnpm start:dev writer"
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - .:/app
    depends_on:
      - kafka

  kafka:
    image: 'bitnami/kafka:2'
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    networks:
      - internal
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - internal
